export const LOADER = 'LOADER';

export const FILTER = 'FILTER';

export const MESSAGEBDGE = 'MESSAGEBDGE';

export const RECEIVEDFILTER = 'RECEIVEDFILTER';

export const REJECTFILTER = 'REJECTFILTER';

export const ACTIONFILTER = 'ACTIONFILTER';

export const EXPERTREFRESH = 'EXPERTREFRESH';

export const CLIENTREFRESH = 'CLIENTREFRESH';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';

export const FCMTOKEN_REQUEST = 'FCMTOKEN_REQUEST';
export const FCMTOKEN_RESPONSE = 'FCMTOKEN_RESPONSE';

export const GETEMAILS_REQUEST = 'GETEMAILS_REQUEST';
export const GETEMAILS_RESPONSE = 'GETEMAILS_RESPONSE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_RESPONSE = 'LOGOUT_RESPONSE';

export const BASICINFO_REQUEST = 'BASICINFO_REQUEST';
export const BASICINFO_RESPONSE = 'BASICINFO_RESPONSE';

export const VERIFICATION_REQUEST = 'VERIFICATION_REQUEST';
export const VERIFICATION_RESPONSE = 'VERIFICATION_RESPONSE';

export const FORGOTOTP_REQUEST = 'FORGOTOTP_REQUEST';
export const FORGOTOTP_RESPONSE = 'FORGOTOTP_RESPONSE';

export const PASSWORD_REQUEST = 'PASSWORD_REQUEST';
export const PASSWORD_RESPONSE = 'PASSWORD_RESPONSE';

export const EMAILVERIFICATION_REQUEST = 'EMAILVERIFICATION_REQUEST';
export const EMAILVERIFICATION_RESPONSE = 'EMAILVERIFICATION_RESPONSE';

export const FORGOTPASSWORD_REQUEST = 'FORGOTPASSWORD_REQUEST';
export const FORGOTPASSWORD_RESPONSE = 'FORGOTPASSWORD_RESPONSE';

export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHNAGE_PASSWORD_RESPONSE = 'CHNAGE_PASSWORD_RESPONSE';

export const PROFILE_REQUEST = 'PROFILE_REQUEST';
export const PROFILE_RESPONSE = 'PROFILE_RESPONSE';

export const MYPROFILE_REQUEST = 'MYPROFILE_REQUEST';
export const MYPROFILE_RESPONSE = 'MYPROFILE_RESPONSE';

export const EDITPROFILE_REQUEST = 'EDITPROFILE_REQUEST';
export const EDITPROFILE_RESPONSE = 'EDITPROFILE_RESPONSE';

export const INVITEUSER_REQUEST = 'INVITEUSER_REQUEST';
export const INVITEUSER_RESPONSE = 'INVITEUSER_RESPONSE';

export const INVITED_REQUEST = 'INVITED_REQUEST';
export const INVITED_RESPONSE = 'INVITED_RESPONSE';

export const MYCIRCALE_REQUEST = 'MYCIRCALE_REQUEST';
export const MYCIRCALE_RESPONSE = 'MYCIRCALE_RESPONSE';

export const EXPERTCIRCLE_REQUEST = 'EXPERTCIRCLE_REQUEST';
export const EXPERTCIRCLE_RESPONSE = 'EXPERTCIRCLE_RESPONSE';

export const CLIENTCIRCLE_REQUEST = 'CLIENTCIRCLE_REQUEST';
export const CLIENTCIRCLE_RESPONSE = 'CLIENTCIRCLE_RESPONSE';

export const REFER_REQUEST = 'REFER_REQUEST';
export const REFER_RESPONSE = 'REFER_RESPONSE';

export const ACTIVE_REQUEST = 'ACTIVE_REQUEST';
export const ACTIVE_RESPONSE = 'ACTIVE_RESPONSE';

export const CONVERSATION_REQUEST = 'CONVERSATION_REQUEST';
export const CONVERSATION_RESPONSE = 'CONVERSATION_RESPONSE';

export const SENT_REQUEST = 'SENT_REQUEST';
export const SENT_RESPONSE = 'SENT_RESPONSE';

export const REJECTED_REQUEST = 'REJECTED_REQUEST';
export const REJECTED_RESPONSE = 'REJECTED_RESPONSE';

export const INVITES_REQUEST = 'INVITES_REQUEST';
export const INVITES_RESPONSE = 'INVITES_RESPONSE';

export const CONNECTIONBADGE_REQUEST = 'CONNECTIONBADGE_REQUEST';
export const CONNECTIONBADGE_RESPONSE = 'CONNECTIONBADGE_RESPONSE';

export const INVITESSTATUS_REQUEST = 'INVITESSTATUS_REQUEST';
export const INVITESSTATUS_RESPONSE = 'INVITESSTATUS_RESPONSE';

export const INVITESACCEPTSTATUS_REQUEST = 'INVITESACCEPTSTATUS_REQUEST';
export const INVITESACCEPTSTATUS_RESPONSE = 'INVITESACCEPTSTATUS_RESPONSE';

export const ACTIONSTATUS_REQUEST = 'ACTIONSTATUS_REQUEST';
export const ACTIONSTATUS_RESPONSE = 'ACTIONSTATUS_RESPONSE';

export const INVITEDSTATUS_REQUEST = 'INVITEDSTATUS_REQUEST';
export const INVITEDSTATUS_RESPONSE = 'IINVITEDSTATUS_RESPONSE';

export const REJECTEDSTATUS_REQUEST = 'REJECTEDSTATUS_REQUEST';
export const REJECTEDSTATUS_RESPONSE = 'REJECTEDSTATUS_RESPONSE';

export const PROFILEUPDATE_REQUEST = 'PROFILEUPDATE_REQUEST';
export const PROFILEUPDATE_RESPONSE = 'PROFILEUPDATE_RESPONSE';
